name: liquidart_test
description: Utilities for writing automated tests for Liquidart applications
version: 3.0.0-b1
homepage: https://github.com/aldrinsartfactory/liquidart
repository: https://github.com/aldrinsartfactory/liquidart
issue_tracker: https://github.com/aldrinsartfactory/liquidart/issues
documentation: https://aldrinsartfactory.github.io/liquidart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  test: ^1.16.8
  matcher: ^0.12.10
  # liquidart: ^5.0.0-b3

# This is removed before being published.
dependency_overrides:
  liquidart:
    path: ../liquidart
