name: liquidart_test
description: Utilities for writing automated tests for Liquidart applications
version: 2.0.0-b2
homepage: https://github.com/aldrinsartfactory/liquidart
repository: https://github.com/aldrinsartfactory/liquidart
issue_tracker: https://github.com/aldrinsartfactory/liquidart/issues
documentation: https://aldrinsartfactory.github.io/liquidart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  test: ^1.3.0
  matcher: '>=0.12.3 <0.14.0'
  liquidart: ^4.0.1-b2

# This is removed before being published.
# dependency_overrides:
#   liquidart:
#     path: ../liquidart