site_name: Liquidart Documentation
site_description: Official Documentation of the Liquidart Project.
site_author: Aldrin Mathew
copyright: Original documentation of Liquidart (previously Aqueduct) written by the StableKernel Team
repo_url: https://github.com/aldrinsartfactory/liquidart/
theme:
  name: material
  logo: images/logo.png
  font:
    text: Roboto
    code: Fira Code
  palette:
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
markdown_extensions:
  - admonition
nav:
  - Welcome : index.md
  - Core Concepts : core_concepts.md
  - Getting Started : getting_started.md
  - Tour : tour.md
  - Best Practices : best_practices.md
  - IntelliJ IDEA Templates : intellij.md
  - Tutorial :
    - 1. Getting Started : tutorial/getting_started.md
    - 2. Reading from a Database: tutorial/executing_queries.md
    - 3. Storing Data in a Database: tutorial/storing_data.md
    - 4. Configuration and Testing: tutorial/writing_tests.md
    # - 5. Authentication and Authorization: tutorial/oauth2.md