name: liquidart
version: 5.0.0-b1
description: A modern HTTP server application framework, ORM and OAuth2 provider with OpenAPI 3.0 integration. Foundation for REST, RPC or GraphQL services. Revival of the AQUEDUCT Project.
homepage: https://github.com/aldrinsartfactory/liquidart
repository: https://github.com/aldrinsartfactory/liquidart
issue_tracker: https://github.com/aldrinsartfactory/liquidart/issues
documentation: https://aldrinsartfactory.github.io/liquidart/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  analyzer: ^1.3.0
  crypto: ^3.0.0
  logging: ^1.0.1
  loner: ^3.0.0-b2
  meta: ^1.3.0
  open_api_data: ^3.0.0-b1
  hasher: ^3.0.0-b1
  path: ^1.8.0
  postgres: ^2.3.2
  pub_cache: ^0.3.0
  pub_semver: ^2.0.0
  safe_yaml: ^4.0.0-b1
  yaml: ^3.1.0
  replica: ^2.0.0-b1

dev_dependencies:
  matcher: ^0.12.0
  test: ^1.16.8
  http: ^0.13.1
  cli_agent: ^2.0.0-b1
  liquidart_test: ^2.0.0-b1
    # path: ../liquidart_test

executables:
  liquidart: liquidart